import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../utils/api';

const ROLES = [
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'React Developer',
    'Node Developer',
    'Java Developer',
    'Python Developer',
    'DevOps Engineer',
    'Data Analyst',
    'AI Engineer'
];

const LEVELS = [
    'Fresher',
    'Junior',
    'Mid',
    'Senior'
];

const MODES = [
    { name: 'Technical', desc: 'Focuses on structural engineering questions, database design, and architecture.', icon: '⚙️' },
    { name: 'HR', desc: 'Behavioral, culture fit, and soft skill questions.', icon: '🤝' },
    { name: 'Coding', desc: 'Solve JavaScript algorithmic tasks in a Monaco code editor.', icon: '💻' },
    { name: 'Mixed', desc: 'A blended experience of coding rounds, technical questions, and HR criteria.', icon: '🧩' }
];

function InterviewSetup() {
    const [selectedRole, setSelectedRole] = useState(ROLES[0]);
    const [selectedLevel, setSelectedLevel] = useState(LEVELS[2]); // Mid default
    const [selectedMode, setSelectedMode] = useState('Technical');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    
    const navigate = useNavigate();

    const handleStart = async () => {
        setLoading(true);
        setError('');
        try {
            const { data } = await api.post('/interview/start', {
                role: selectedRole,
                experienceLevel: selectedLevel,
                mode: selectedMode
            });
            navigate(`/interview/${data._id}`);
        } catch (err) {
            setError(err.response?.data?.message || 'Failed to start interview. Ensure you have uploaded a resume first!');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="max-w-3xl mx-auto py-8 px-4">
            <div className="bg-white p-8 rounded-3xl shadow-xl border border-slate-100 space-y-8">
                <div className="text-center">
                    <h2 className="text-3xl font-extrabold text-slate-800 tracking-tight mb-2">Configure Practice Session</h2>
                    <p className="text-slate-500 text-sm">Select the parameters to customize the questions generated by Claude AI</p>
                </div>

                {error && (
                    <div className="bg-red-50 border-l-4 border-red-500 text-red-700 p-4 rounded-lg text-sm flex items-start gap-2 shadow-sm animate-bounce">
                        <span>⚠️</span>
                        <span>{error}</span>
                    </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Role Selection */}
                    <div className="space-y-2">
                        <label className="block text-xs font-bold text-slate-500 uppercase tracking-widest">Select Target Role</label>
                        <select 
                            value={selectedRole} 
                            onChange={(e) => setSelectedRole(e.target.value)}
                            className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none text-slate-700 font-semibold"
                        >
                            {ROLES.map((r, i) => <option key={i} value={r}>{r}</option>)}
                        </select>
                    </div>

                    {/* Level Selection */}
                    <div className="space-y-2">
                        <label className="block text-xs font-bold text-slate-500 uppercase tracking-widest">Experience Level</label>
                        <select 
                            value={selectedLevel} 
                            onChange={(e) => setSelectedLevel(e.target.value)}
                            className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-2 focus:ring-primary-500 outline-none text-slate-700 font-semibold"
                        >
                            {LEVELS.map((l, i) => <option key={i} value={l}>{l}</option>)}
                        </select>
                    </div>
                </div>

                {/* Mode Selection Grid */}
                <div className="space-y-3">
                    <label className="block text-xs font-bold text-slate-500 uppercase tracking-widest">Interview Mode / Category</label>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        {MODES.map((mode, i) => (
                            <div 
                                key={i}
                                onClick={() => setSelectedMode(mode.name)}
                                className={`p-5 rounded-2xl border-2 text-left cursor-pointer transition-all flex gap-4 ${
                                    selectedMode === mode.name 
                                        ? 'border-primary-600 bg-primary-50/30' 
                                        : 'border-slate-100 hover:border-slate-300 bg-slate-50/50'
                                }`}
                            >
                                <span className="text-3xl bg-white w-12 h-12 flex items-center justify-center rounded-xl shadow-sm border border-slate-100">{mode.icon}</span>
                                <div className="space-y-1">
                                    <h4 className="font-bold text-slate-800 text-sm">{mode.name}</h4>
                                    <p className="text-slate-400 text-xs leading-normal">{mode.desc}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <button
                    onClick={handleStart}
                    disabled={loading}
                    className="w-full bg-primary-600 text-white py-4 rounded-2xl font-bold hover:bg-primary-700 transition-all shadow-lg shadow-primary-500/20 active:scale-95 flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50 disabled:pointer-events-none"
                >
                    {loading ? "Generating Session..." : "Launch Interview"}
                </button>
            </div>
        </div>
    );
}

export default InterviewSetup;
